os:
  - linux
  # - osx
language: python
python:
  # - "3.4" shipped with outdated pip that cannot install pyqt
  - "3.5"
before_install:
  - pip install --upgrade pip
  - pip install pyqt5
install: python setup.py install
script: python setup.py test
